### ISSUE TITLE
Why don't you fail properly?

### ISSUE THREAD

**Issue by kwugirl** [reedsport-computer-repair/straw#10]
I broke something in the code, but running `rake multiverse` returned 0 for the status code.

Why don't you :heart: Unix?

**Comment by tkrajcar** [comment]
Subscribing. I run straw inside Docker on a separate airgapped network to ensure my privacy, and need to be able to monitor my test runs using only commands with three or less characters in their names. This is an essential feature for my very common use case.

**Comment by thejonanshow** [comment]
:+1:
